### ISSUE TITLE
Images shown twice in collection mode

### ISSUE THREAD

**Issue by Scunkaneli** [fnagel/generic-gallery#13]
Hey there,

when creating a gallery page using collection mode of generic_gallery, it works very good and all images are displayed like they should. If I now apply my 2-column layout to this page (via Backend-Layout), the layout of the gallery page changes (that's good) *but* every image is now shown twice! So before it was `image-1 image-2 image-3` and now it's `image-1 image-2 image-3 image-1 image-2 image-3`. 

This issue does not occur when selecting all files using mass mode (so that's a workaround). Collection mode is working correctly without applying the (2-column) Backend-Layout.

Setup: CMS 8.7.1, PHP 7.1.4, generic_gallery 2.1.0. I can't confirm nor deny if the issue existed on previous versions of Typo3 / PHP / the extension.

Thanks for your great work, I really love the extension!

**Comment by fnagel** [comment]
Sorry for the late response. Too much workload atm.

Are you using the default templates? Are you sure this happens only with specific BE layouts? 
Are you able to reproduce this error in a blank instance of TYPO3? Or a introduction package installation?

**Comment by Scunkaneli** [comment]
I can confirm it only happens when using a BE layout that splits the page into two containers. I am not using the default template, but the only change I did was editing the <li class> to another bootstrap value. I will test and report back. I can confirm duplication does not happen to the single container layout.

I will try to reproduce the error in a blank instance and report back (could take a couple of days)

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by Scunkaneli** [comment]
Sadly, no. I am not able to test it in a blank instance. The only thing I was able to find out is that they get duplicated only when using my backend layout which creates two containers on the front end. I suspect the line `<f:widget.paginate objects="{collection}" as="items" configuration="{itemsPerPage: 100}">` in Templates\GalleryCollection\Show.html causes the problem - it seems to count double as much items as it would need to show the pictures right. I was not able to find any reason why this would happen or any evidence that it is really fixed when modifying this passage.

**Comment by fnagel** [comment]
Strange enough. So when removing the paginate VH it works as expected?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
