### ISSUE TITLE
typo3 V8 TCA Migrations needed

### ISSUE THREAD

**Issue by hkremer** [fnagel/generic-gallery#14]
Hello, In typo3 v8 some TCA migrations are needed for generic-gallery 2.1.0.
In typo3 v8.7 in het install tool the next migrations need to be applied. These should be fixed in extension itself.

The icon path of wizard "RTE" from TCA table "tx_generic_gallery_content['columns']['bodytext']['config']['wizards']['RTE']['icon']"has been migrated to tx_generic_gallery_content['columns']['bodytext']['config']['wizards']['RTE']['icon']" = 'actions-wizard-rte'.

RTE configuration via 'defaultExtras' options are deprecated. String "richtext:rte_transform[mode=ts_css]" in TCA tx_generic_gallery_content['columns']['bodytext']['defaultExtras'] was changed to options in tx_generic_gallery_content['columns']['bodytext']['config']

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_generic_gallery_content['columns']['starttime']['l10n_mode'] and changed to tx_generic_gallery_content['columns']['starttime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_generic_gallery_content['columns']['endtime']['l10n_mode'] and changed to tx_generic_gallery_content['columns']['endtime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_generic_gallery_pictures['columns']['starttime']['l10n_mode'] and changed to tx_generic_gallery_pictures['columns']['starttime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'mergeIfNotBlank' was removed in TCA tx_generic_gallery_pictures['columns']['endtime']['l10n_mode'] and changed to tx_generic_gallery_pictures['columns']['endtime']['config']['behaviour']['allowLanguageSynchronization'] = true

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_generic_gallery_content['columns']['starttime']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_generic_gallery_content['columns']['endtime']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_generic_gallery_pictures['columns']['starttime']['config']

The TCA setting 'renderType' => 'inputDateTime' was added in TCA tx_generic_gallery_pictures['columns']['endtime']['config']

The link wizard has been migrated to a 'renderType' => 'inputLink '. It has been migrated from TCA table "tx_generic_gallery_pictures['columns']['link']['config']['wizards']['link']" to "tx_generic_gallery_pictures['columns']['link']['config']['renderType'] = 'inputLink'".

The RTE fullscreen wizard in TCA has been migrated to a 'fieldControl' = 'fullScreenRichtext'. It has been migrated from TCA "tx_generic_gallery_content['columns']['bodytext']['config']['wizards']['RTE']" to "tx_generic_gallery_content['columns']['bodytext']['config']['fieldControl']='fullScreenRichtext'".

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_generic_gallery_content['columns']['starttime']['config']['max']

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_generic_gallery_content['columns']['endtime']['config']['max']

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_generic_gallery_pictures['columns']['starttime']['config']['max']

The config option 'max' has been removed from the TCA for renderType='inputDateTime' in tx_generic_gallery_pictures['columns']['endtime']['config']['max']

**Comment by fnagel** [comment]
Valid request but most of this issues won't be fixed until 7.6 is no longer supported by this extension as fixing / testing the TCA for all versions is no fun at all. Those warnings / migrations should be no issue in a productive environment.

I would gladly merge any tested PR to fis those issues!
