### ISSUE TITLE
The Extension don't work 

### ISSUE THREAD

**Issue by NiklasLazinbee** [fnagel/generic-gallery#16]
Hello,
I installed the extension, add static TS and put the plugin on a page. I see the pictures in frontend, but there is no gallery function, only a list of pictures. 
How is it possible to create a gallery without any javascript? No JS and CSS is loaded an there are no JS or CSS files in the extension code. What went wrong?

Best regards 
Niklas

**Comment by fnagel** [comment]
This extension does not come with JS / CSS. It's more like a framework for any gallery script out there.

You could use the Bootstrap 3 templates (see https://github.com/fnagel/generic-gallery/blob/master/Configuration/TypoScript/Examples/Bootstrap/setup.txt) but need to add the Bootstrap CSS and JS yourself.

**Comment by NiklasLazinbee** [comment]
Oh thanks, I don’t read or find this tip.

Best regards,
Niklas
