### ISSUE TITLE
Bad Image quality when expanding picture

### ISSUE THREAD

**Issue by Scunkaneli** [fnagel/generic-gallery#19]
Since I updated to TYPO3 8.7.16 LTS from 8.7.13, creating new or modifying old "Default" style gallerys in Mode 2 would cause in a broken image structure. I am sure the "Bootstrap Image Slider" layouts also had the same issues: 
On the frontend, both the `<a class="gallery">` and the `<img>`, which it contains, shared the exact same image link, which was thumbnail sized and thus very low quality. Using a lightbox on top of this extension or trying to open the picture in full screen would cause the image to look terrible, as the original quality picture was linked nowhere.
Previously, the `<a href="...">` tag contained a link to the original high quality picture which the lightbox/fullscreen would use, but this was no longer the case.

I was able to fix the problem by editing some Templates and Partials of this extension, but before proposing it to merge with master, I think it would be better to hear if anyone else also experienced the same issue - there is always the possibility that my issue was not caused directly by the TYPO3 update but rather in conjunction with another (incompatible?) extension.

**Comment by fnagel** [comment]
Sounds like something is broken within your instance. Using pretty much standard Fluid functionality in the default templates. Can you post how your changes look like? 

Perhaps updating to a newer TYPO3 version helps (I experienced some issues with 8.7.17).

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by Scunkaneli** [comment]
Well, the issue still persists on my system. The issue is with `<f:link.typolink parameter="{item.link}" class="gallery">` in Partials/GalleryItem/Image.html. This does not output the URL to the original image, but to the processed version of it. You can fix that by replacing it with `<a class="gallery" href="fileadmin/{item.image.identifier}">`

**Comment by fnagel** [comment]
Still not sure why you having those issues but using `href="fileadmin{item.image.identifier}"` looks like a very bad idea. What about using `item.image.publicUrl`?

Did you try to debug the issue within the `getLink` method in the GalleryItem model?

**Comment by Scunkaneli** [comment]
I just tried it again. Using `<f:link.typolink parameter="{item.link}">` puts the processed (bad) version of the image in the `<a href="">`. Using `<a href="fileadmin{item.image.identifier}">` uses the correct version of the image in the href. I tried your idea with `item.image.publicUrl` and it works well too; it uses the correct, big original image. 

Sadly I have no idea how I should debug it; I did not try that. Of course including fileadmin in the Partial is bad practice but I was happy I got it working at all. As your idea is far better/cleaner and works fine too I now did switch back to using typolink using `<f:link.typolink parameter="{item.image.publicUrl}">` 
Thanks! :)

**Comment by fnagel** [comment]
That's interesting, as the `getLink` Method _should_ use `image.publicUrl` in most cases, see https://github.com/fnagel/generic-gallery/blob/master/Classes/Domain/Model/GalleryItem.php#L164-L179

Would be of great interest to see what the values of some of those properties in the above linked code snippet are. Just add a var_dump and see what happens ;-)

**Comment by Scunkaneli** [comment]
Where do I have to add `var_dump` exactly? In GalleryItem.php, Image.html or somewhere different?

**Comment by fnagel** [comment]
Somewhere in the lines I've linked above. Try something like `var_dump($this);` but I guess without same basic PHP knowledge this will be a hard task :-/

**Comment by Scunkaneli** [comment]
Yes, I agree with you on that. I tried adding `var_dump($this);` and `$content=var_export($this,true)
echo $content;` to L175 of GalleryItem.php, but was not able to find where the result gets displayed or exported to.

**Comment by fnagel** [comment]
Ahh okay, try the TYPO3 debugger: `\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump();`

**Comment by Scunkaneli** [comment]
I added that line to L175 of the same file too but I again can't find a
place where something changed. Where should I be able to see the output
of the command?


Am 23.11.2018 um 21:56 schrieb Felix Nagel:

**Comment by fnagel** [comment]
It should pop-up within the page (on the top). Try placing it before the if, just to test if it's called at all.

**Comment by Scunkaneli** [comment]
As usually it was my fault it was not working. var_dump still does not work, but I was able to get output from `\TYPO3\CMS\Extbase\Utility\DebuggerUtility::var_dump();`. Sadly I don't think that it did work right: The output was a big list with many entries, but every entry was [the same](https://i.imgur.com/vonxscX.jpg).

**Comment by fnagel** [comment]
Looks like those are all virtual items, that's why they look similar. Try debug `$this->imageReference`, they should have different image property values. 

And try debugging which return statement is used.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
