### ISSUE TITLE
Overwrite FAL metadata from file reference

### ISSUE THREAD

**Issue by nabossha** [fnagel/generic-gallery#2]
Is there a way to access the metadata of FAL-items (i.e. title, description) and get it into the template? i am currently struggling to achieve this. Would be a very useful addition to this ext!

**Comment by fnagel** [comment]
That's already possible and one of the main features of this extension!

Documentation: https://github.com/fnagel/generic-gallery/blob/master/Documentation/Configuration/Template/Index.rst#fal-metadata

Example code: https://github.com/fnagel/generic-gallery/blob/master/Resources/Private/Partials/GalleryItem/Copyright.html

**Comment by nabossha** [comment]
thank you for these - i should have written my question more specifically because what you write is absolutely correct but where i'm struggling is:
When metadata like title or description are overwritten in the local record (using "multiple files" or "file collection" in the plugin) these values are not available in any of my {item} porperties. 
is there a way to access these "local" values (which is what most editors are using...). when using normal tt_content image elements the local title/description also override FAL-metadata.

**Comment by fnagel** [comment]
I can confirm this isssue. Working on a fix...

**Comment by fnagel** [comment]
I've just pushed a fix for this issue. Please test and give feedback!

**Comment by nabossha** [comment]
thanks a lot for this fix - it's now working as expected using TYPO3 6.2.15

**Comment by fnagel** [comment]
Sure, glad it worked and thanks for the report! I will wait until next week for TYPO3 7.5, do some testing and than pushing a new version to TER.

Thanks a lot for your donation! Really appreciated!
