### ISSUE TITLE
php 7.2.5 / core 8.7.13

### ISSUE THREAD

**Issue by martens-web-netz-de** [fnagel/generic-gallery#20]
Hi,
are there any known issues which prevent raising requirements (master) to: ``{
    "php": ">=5.5.0,<=7.2.99",
    "typo3/cms-core": ">=7.2.0,<=8.7.99"
  }``

Regards,
Markus

**Comment by fnagel** [comment]
Not really. Extension is currently untested in PHP 7.2 but I'm happy for any feedback if it works.

**Comment by fnagel** [comment]
Fixed the TYPO3 CMS constraint in master branch. Can you confirm the extension is compatible with PHP 7.2?

**Comment by martens-web-netz-de** [comment]
Hi @fnagel 

not yet with certainty. project priorities have shifted, but generic-gallery is still one of them 😉
