### ISSUE TITLE
Error in BE after installing generic-gallery

### ISSUE THREAD

**Issue by vigri** [fnagel/generic-gallery#21]
Hello,

right after installing this extension I get an error when inserting the plugin into a page:

"An error occurred trying to process items for field "Gallery type" (No typoscript settings available.)."

I found a similar problem on forge.typoe (https://forge.typo3.org/issues/76341#note-4) but this one was in combination with TV.

Can you give a hint please how to solve this?

PHP: 7.0.32
Typo3: 8.7.19

Regards

**Comment by fnagel** [comment]
Can you give me some insight on your instance? GG version? Did you tried the latest master from GitHub?

Please post your TS configuration and how you include it.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
