### ISSUE TITLE
Compatibility with TYPO3 9 LTS

### ISSUE THREAD

**Issue by pixelbreit** [fnagel/generic-gallery#25]
Will there be a Version of generic-gallery compatible with TYPO3 9 LTS in the near future?

**Comment by fnagel** [comment]
Definitely! Already started a branch, but needs some more love (but should work except for the new speaking URL feature). Any feedback is welcome!

https://github.com/fnagel/generic-gallery/tree/typo3-9

**Comment by fnagel** [comment]
Just worked on this a little and it seems the branch is fully working except for the speaking URL feature. Problem is that I need to cover all parameters with `aspects` rules, but the route segment `{item}` can may be a persisted DB record or a virtual identifier. Not sure how to proceed here.

Anyway, are you (or anybody else) able to provide some feedback regarding the branch? As soon as some positive feedback has been submitted, I'm willing to release a new version!

**Comment by fnagel** [comment]
> Unfortunately, I'm currently still in project stress. 

I'm very aware of that situation, so no hard feelings :-D 

> The loss of RealURL for TYPO3 CMS 9 is a real disappointment.

Ohh, I was not aware that there are no plans at all, but seems so: https://github.com/dmitryd/typo3-realurl/issues/632

**Comment by msollmann** [comment]
Are there any news about the 9 compatibility? Just for planning... :-)

**Comment by fnagel** [comment]
@msollmann The version in the `typo3-9` branch is already compatible with TYPO3 9.5. The speaking URL feature is not fully complete but that's something not really needed for the base functionality itself.

I would love to publish a new version to TER but would need some more feedback before. So please, check it out, give some feedback and the new version will be released next week :-D

**Comment by msollmann** [comment]
Currently I have no 9.5 installation to test it. Probably in the next months... sorry.

**Comment by msollmann** [comment]
After short testing of 2.2.1-dev on TYPO3 9: No problems detected.

**Comment by fnagel** [comment]
Just released version 3.0.0 with TYPO3 9.5 support and fully functional routing! Yeahh!
