### ISSUE TITLE
PHP 7.3 / 7.4 support

### ISSUE THREAD

**Issue by fnagel** [fnagel/generic-gallery#28]
Needs testing.

**Comment by liayn** [comment]
Did not spot any issue with v7.4 by inspecting the whole code manually. It would be nice if you could open the ext up for at least 7.3. Thanks.

**Comment by fnagel** [comment]
Any experience with 7.3 and / or 7.4 while using it? Or just "by reading"?

**Comment by liayn** [comment]
Well, I'm about to install it locally with 7.3.
But to be very honest: if phpstorm does not complain about anything, chances are very high that everything is in good shape. (At least that's my experience)

so installation would be easier (with composer) if you would allow the PHP version. If any hick-up happens it should be rather easy to fix.

**Comment by liayn** [comment]
Thanks. I suggest we close this ticket and I'll create a new one in case a problem pops up.

**Comment by fnagel** [comment]
@liayn Any feedback on PHP 7.3 so far? I'm about to do a 10 LTS compatibility release and it would be great to include PHP 7.3 support.

**Comment by liayn** [comment]
> it would be great to include PHP 7.3 support.

Well, I this would not only be great, actually I see this as a hard requirement, or better said: PHP 7.4 must be the sole goal.

https://www.php.net/supported-versions.php
PHP 7.2 is in sec-fix-only mode and officially dead in 7 months.

So from what I can tell so far I have no issues. But I did not test in every corner.
My suggestion: open it up to 7.4 and fix one or the other error in case they pop up.

**Comment by fnagel** [comment]
Thanks for the feedback! Just released 4.2.0 with PHP 7.3 support.

**Comment by liayn** [comment]
Nice!
