### ISSUE TITLE
FE error when images are disabled

### ISSUE THREAD

**Issue by msollmann** [fnagel/generic-gallery#29]
If the user disables an gallery image (not one of the tx_generic_gallery_items but the "images" item inside the "tx_generic_gallery_items" item) an FE error occurs:

"Call to a member function getOriginalResource() on null"

The reason is in the model GalleryItem.php:
```
public function getImage()
{
        **if ($this->image === null) {
            return $this->imageReference->getOriginalResource()->getOriginalFile();**
}
```

**Comment by fnagel** [comment]
Thanks for you bug report!

Would you mind testing this commit: b6fc34a21546dcbf9218663643740250af216901

**Comment by msollmann** [comment]
It works! Thank you for solving this issue!

**Comment by fnagel** [comment]
Thanks for the feedback!
