### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by PatrickKalka-SeriousByte** [fnagel/generic-gallery#30]
I've was confronted with the error 

requires php >=5.4.0,<7.1 -> your PHP version (7.4.5) overridden by "config.platform.php" version (7.4) does not satisfy  that requirement.

**Comment by fnagel** [comment]
Seems you are using an outdated version (as 4.2.0 works with PHP 7.3, see https://github.com/fnagel/generic-gallery/blob/master/composer.json#L22) but you're right: PHP 7.4 is not officially supported yet.

Anyway, which PHP version are you actually using? If its PHP 7.4 you could try to configure  `config.platform.php` to 7.3 and do some testing. I'm pretty sure the extension should work without issues. If so, I'm willing to push a compatible patch version soon.

**Comment by fnagel** [comment]
Any feedback on this issue?
