### ISSUE TITLE
No setup.txt Error

### ISSUE THREAD

**Issue by tklmn** [fnagel/generic-gallery#32]
In the log files you will get this error:

Wed, 30 Sep 2020 11:20:40 +0200 [WARNING] request="425c7c3dd9d1f" component="TYPO3.CMS.Core.TypoScript.Parser.TypoScriptParser": File "EXT:generic_gallery/Configuration/TypoScript/Examples/setup.txt" was not found. 

In the setup.typoscript you have to change
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:generic_gallery/Configuration/TypoScript/Examples/setup.txt">
to
<INCLUDE_TYPOSCRIPT: source="FILE:EXT:generic_gallery/Configuration/TypoScript/Examples/setup.typoscript">

**Comment by fnagel** [comment]
That should be fixed in https://github.com/fnagel/generic-gallery/commit/a7aa5d0ecab8ae7785f6f9d954451fa1073db162 (which is not yet included in a TER release). Can you confirm?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
