### ISSUE TITLE
Gallery type not selectable

### ISSUE THREAD

**Issue by hanvanloon** [fnagel/generic-gallery#33]
Hi, I just tried your great looking extension, I used the extension manager upload of the zip fil in Typo3 LTS 10.4. But after selecting the plug-in, the gallery type did not provide any selectable types. As a newbie I am lost. 
![generic-gallery-error1](https://user-images.githubusercontent.com/72971912/96242551-de624480-0fa3-11eb-93cd-0b9c7e8bd5ed.jpg). Thanks for any help. Han

**Comment by fnagel** [comment]
Did you include the default TypoScript setup? See https://github.com/fnagel/generic-gallery/blob/master/Documentation/Administration/Index.rst

**Comment by hanvanloon** [comment]
Hi. Thanks for the quick reply. As a newbie using an installation package from jweiland.net, I have virtually no Typoscript knowhow. Do I put the 2 things in?:   EXT:generic_gallery/Configuration/Routes/Default.yaml   AND static TS Generic Gallery: default. Do I enter them in Konfiguration or elsewhere?

**Comment by hanvanloon** [comment]
Konfiguration....
![Konfiguration](https://user-images.githubusercontent.com/72971912/96333365-a9202a00-1069-11eb-8210-258c2ce6ecc0.jpg)

**Comment by fnagel** [comment]
That screenshot is TYPO Configuration Variables (CONF VARS). You need to check TypoScript Configuration using the "Template" Module. Use the "TypoScript Object Browser" from there, but I guess you did not add anything yet. 

Search for a TS template on the root page, adding "Generic Gallery: default" as a static template. The yaml is for speaking URLs and needs to be included in the Site Configuration yaml.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by hanvanloon** [comment]
Hello Felix
As I am an incompetent Typo3 programmer, I asked Jochen Weiland  
(hosting service) for some help as I could not see how to include the  
instruction within their Typo3 template instance, but they have not  
answered. So it is unfortunately in limbo....
best regards/mi freundliche Grüsse
Han


Quoting Felix Nagel <notifications@github.com>:

**Comment by fnagel** [comment]
Ahhh too bad and I'm not sure how to be more helpful here without access to the system...

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Comment by hanvanloon** [comment]
Hi Felix
Thanks for your earlier reply. The Weiland team finally entered the  
code for the generic gallery. I quickly tried it using the slider  
setting. The pictures appear in a vertical column, no slide function.  
The picture numbers appear also in a vertical column above the pictures.

I am travelling from tomorrow and will be back on 5 June. I will  
pursue the matter further then and request your patience nd possible  
help then.

best regards/mit freundliche Grüsse
Han


Quoting Felix Nagel ***@***.***>:

**Comment by fnagel** [comment]
@hanvanloon Sounds like you missing needed JS / CSS assets. The examples need a working Twitter Bootstrap setup as its using TBS for creating a slider, gallery, etc. If you have a custom gallery script you will need to add an own template.
