### ISSUE TITLE
SQL error: 'Incorrect integer value: '' for column `c1_SQL01`.`tt_content`.`tx_generic_gallery_collection` at row 1'

### ISSUE THREAD

**Issue by SicorDev** [fnagel/generic-gallery#35]
Hi there,

I got the above error when trying to copy a newsletter with lots of elements, gridelements and images amongst others. Actually no gallery though...

To make it go away I had to deactivate the inline usage of sys_file_collection in the extension options, as well as add 

'default' => 0,

to the config for 'tx_generic_gallery_collection' in

generic_gallery/Configuration/TCA/Overrides/tt_content.php

No idea how to fix the inline variant...

Greetings,
Manuel

**Comment by fnagel** [comment]
Hey Manuel! 

Which version of TYPO3 are you using? 

Sounds this could be an issue with the mode of your SQL mode, see 
https://git.typo3.org/Packages/TYPO3.CMS.git/blob/c5f567c36689e197c6b25e9e2d3adfe50c12f610:/INSTALL.md#l305
https://forge.typo3.org/issues/54883

If SQL mode is correct, please try if this solution helps: https://stackoverflow.com/a/50138799/991681

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Comment by fnagel** [comment]
Afaik strict mode is not supported by TYPO3 CMS or am I missing something? Anyway, if this does not break anything we can fix it. Which TYPO3 version are you using?

**Comment by PeaceSfiSh** [comment]
I use TYPO3 v10 and v11. 
The 'default" => 0 configuration is also used in the core. You can find it context of a record relation in the pages TCA for the field 'l10n_parent'. 
Thanks.

**Comment by fnagel** [comment]
It's really hard to find some proper documentation for this. Nothing good in the official docs. EXT:news does not use a default for group` and `inline` type fields: https://github.com/georgringer/news/blob/main/Configuration/TCA/tx_news_domain_model_news.php and neither does https://github.com/TYPO3GmbH/blog/blob/master/Configuration/TCA/

Is this only needed for the `tx_generic_gallery_collection` field? And if so, for both `type`s (`group` and `inline`)? In the core, I've seen fields with a default config for group type fields.

For TYPO3 10 there is a release in the making but for TYPO3 11 I need to backport some more changes, which will take some more time.

Some references:
https://forge.typo3.org/issues/68397

**Comment by PeaceSfiSh** [comment]
Take your time and put it into the next release. I put a override into my sitepackage as a workaround.

PS: good research related to this topic, thanks

**Comment by fnagel** [comment]
@fnagel Any feedback on where the fix is needed? 

Is this enough? 
https://github.com/fnagel/generic-gallery/commit/9be182143204444033800fa18e7137ebf11df932

Or is it needed here too?
https://github.com/fnagel/generic-gallery/blob/9be182143204444033800fa18e7137ebf11df932/Configuration/TCA/Overrides/tt_content.php#L100-L110

**Comment by PeaceSfiSh** [comment]
I just traced it in v10. The result it's only needed for the group type.

**Comment by fnagel** [comment]
Thanks for the feedback! TER release for 4.x is on its way :-)
