### ISSUE TITLE
Desired FileCollection type "images" is not in the list of available FileCollections.

### ISSUE THREAD

**Issue by wd-philipp** [fnagel/generic-gallery#36]
Hello,

i get this error on the gallery frontend page when an image collection with type "default gallery" is integrated with the type "images".

I use TYPO3 v10.4.14

Greetings,
Philipp

**Comment by fnagel** [comment]
Can you add a screenshot of the BE and FE? Not quite sure what the error is exactly. Thanks!

**Comment by wd-philipp** [comment]
Hey, here are the error from the fronend and the plugin in the backend.

![fe_error](https://user-images.githubusercontent.com/78961888/111822823-875ef380-88e4-11eb-920f-05760c220c44.JPG)
![backend](https://user-images.githubusercontent.com/78961888/111822846-8ded6b00-88e4-11eb-9178-b6a022f535f0.JPG)

**Comment by fnagel** [comment]
Thanks. I can reproduce this and will try to find a solution!

**Comment by fnagel** [comment]
Should be fixed in the master branch. Please test latest commit c31810e7ae90c69da2f80882ea4eab230cb85337 and give feedback!

**Comment by wd-philipp** [comment]
thanks for the fast response & solution!
it works ;-)

**Comment by fnagel** [comment]
You're very welcome! Thanks for reporting and the fast feedback :-)

Tagged release and TER version is about to be released!
