### ISSUE TITLE
Feature - make existing sys_file_collection selectable

### ISSUE THREAD

**Issue by PeaceSfiSh** [fnagel/generic-gallery#37]
Would be nice if existing file collections (sys_file_collection) are selectable in the plugin settings.
Currently a new file collection is created with every and related to the content element.

**Comment by fnagel** [comment]
This should already be possible when switching the `add_image_collection` EM config.

**Comment by fnagel** [comment]
Any feedback on this issue?

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.

**Comment by PeaceSfiSh** [comment]
Thank you for the hint, it works very well. Now I'm able to extend EXT:generic_gallery and drop my own implementation.

And sorry for the late reply. 😬

**Comment by fnagel** [comment]
I'm glad it works for you! Ping me if you need anything more to ease up extending.

And thanks for the feedback :-)
