### ISSUE TITLE
TYPO3 11 support

### ISSUE THREAD

**Issue by fnagel** [fnagel/generic-gallery#38]
This is a work in progress task, see https://github.com/fnagel/generic-gallery/tree/typo3-11

**Comment by fnagel** [comment]
Merged a working version to master branch. Please test and give feedback!

**Comment by fnagel** [comment]
Version 5.0.0 is TYPO3 11 LTS compatible.

**Comment by dfpsoeew** [comment]
Not sure if this error is my fault but I'm getting a parse error in backend after updating to 5.0.0 (running PHP 7.4 by the way):

> (1/1) ParseError
> 
> syntax error, unexpected '|', expecting ';' or '{'
> in ...\typo3conf\ext\generic_gallery\Classes\Domain\Model\GalleryItem.php line 88
> 
> ```
>     {
>         $this->textItems = new ObjectStorage();
>     }
> 
>     public function getIdentifier(): int|string
>     {
>         $identifier = $this->getUid();
> 
>         if ($identifier === null) {
> ```
