### ISSUE TITLE
PHP Warning in PageLayoutViewHook.php

### ISSUE THREAD

**Issue by matcolton** [fnagel/generic-gallery#40]
After installing the current version (5.1.0) of generic_gallery with PHP 7.4 and  Typo3 11 the following warning is shown:
Undefined array key "BACK_PATH" in /ext/generic_gallery/Classes/Backend/Hooks/PageLayoutViewHook.php line 173
It refers to the following code:
```
$this->imagePreviewHtml = BackendUtility::thumbCode(
    $this->data,
    'tt_content',
    'tx_generic_gallery_images',
    $GLOBALS['BACK_PATH']
 );
```
The method thumbCode only accepts three params anyway. The fix is to remove the last parameter.

**Comment by fnagel** [comment]
Afaics the `thumbCode` method does except a lot more arguments but `$backPath` is no longer in use (see screenshot from TYPO3 11.5.8). Seems like this is the case for TYPO3 10 too.

![image](https://user-images.githubusercontent.com/116824/160715726-0a2e72ca-afd2-4298-aaac-30832b755792.png)

Removed the useless third parameter. Thanks for reporting! I've pushed a change to `master` branch. Would you mind to test if this works for you?
