### ISSUE TITLE
PHP Warning in AbstractController.php

### ISSUE THREAD

**Issue by matcolton** [fnagel/generic-gallery#41]
After installing the current version (5.1.0) of generic_gallery with PHP 7.4 and Typo3 11 the following warning is shown:
PHP Warning: Undefined array key "_LOCALIZED_UID" in ext/generic_gallery/Classes/Controller/AbstractController.php line 85

`$this->uid = $data['_LOCALIZED_UID'] ?: $data['uid'];`

To fix this warning change the line to:

`$this->uid = array_key_exists('_LOCALIZED_UID', $data) && $data['_LOCALIZED_UID'] ?: $data['uid'];`

**Comment by fnagel** [comment]
Hello @matcolton, thanks for your contribution! 

I thought those kind of warnings are more a PHP 8.x issue. Anyway, I've pushed a change to `master` branch. Would you mind to test if this works for you?
