### ISSUE TITLE
PHP Warning in GalleryCollectionController.php

### ISSUE THREAD

**Issue by matcolton** [fnagel/generic-gallery#42]
After installing the current version (5.1.0) of generic_gallery with PHP 7.4 and Typo3 11 the following warning is shown:
PHP Warning: Undefined array key "paginate" in ext/generic_gallery/Classes/Controller/GalleryCollectionController.php line 39

`$this->currentSettings['paginate']['itemsPerPage'] ?: 10,`

To fix this warning change the line to:

`array_key_exists('paginate', $this->currentSettings) && $this->currentSettings['paginate']['itemsPerPage'] ?: 10,`

**Comment by fnagel** [comment]
Hello @matcolton, thanks for your contribution! I've pushed a change to `master` branch. Would you mind to test if this works for you?

**Comment by matcolton** [comment]
Great, works perfectly now. Thanks!
