### ISSUE TITLE
Installation Generic_Gallery Typo3 11.5.22 php 8.0

### ISSUE THREAD

**Issue by PeterEdelmann** [fnagel/generic-gallery#52]
Try to install Generic_Gallery, After installation and adding static TS Generic Gallery i get an exception '1316104317 Typo3\CMS\Extbase\Mvc\Exception. I am using Typo3 Ver.11.5, so I tried to add EXT:generic_gallery/Configuration/Routes/Default.yaml in config.yaml. (import (resources....) after RouteEnhancers. Then I got an exception "Symfony\Component\Yaml\Exception\ParseException You cannot define a mapping item when in a sequence at line 2 (near "NewsPlugin:")
May someone knows, what I am doing wrong and/or can give me an advice, how to add the default.yaml to my site configuration.
Thanks a lot.
Peter

**Comment by fnagel** [comment]
> After installation and adding static TS Generic Gallery i get an exception '1316104317 Typo3\CMS\Extbase\Mvc\Exception.

Please post the complete exception stack trace. Or post a link.


> "Symfony\Component\Yaml\Exception\ParseException You cannot define a mapping item when in a sequence at line 2 (near "NewsPlugin:")

Can you please post your complete routing yaml file? Looks like there is an general parsing issue but I'm 100% sure its not within the GG file: https://github.com/fnagel/generic-gallery/blob/master/Configuration/Routes/Default.yaml

> May someone knows, what I am doing wrong and/or can give me an advice, how to add the default.yaml to my site configuration.

Nothing special here. Just add this to the end of your site configuration yaml or in one of your extension imports:

```- { resource: "EXT:generic_gallery/Configuration/Routes/Default.yaml" }```

**Comment by PeterEdelmann** [comment]
Hallo Herr Nagel, anbei 2 Dateien, Weiss nicht ob lesbar, bin am Tablet. Von meinem Huawei-Tablet gesendet-------- Originalnachricht --------Betreff: Re: [fnagel/generic-gallery] Installation Generic_Gallery Typo3 11.5.22 php 8.0 (Issue #52)Von: Felix Nagel An: fnagel/generic-gallery Cc: PeterEdelmann ,Author 

After installation and adding static TS Generic Gallery i get an exception '1316104317 Typo3\CMS\Extbase\Mvc\Exception.

Please post the complete exception stack trace. Or post a link.

"Symfony\Component\Yaml\Exception\ParseException You cannot define a mapping item when in a sequence at line 2 (near "NewsPlugin:")

Can you please post your complete routing yaml file? Looks like there is an general parsing issue but I'm 100% sure its not within the GG file: https://github.com/fnagel/generic-gallery/blob/master/Configuration/Routes/Default.yaml

May someone knows, what I am doing wrong and/or can give me an advice, how to add the default.yaml to my site configuration.

Nothing special here. Just add this to the end of your site configuration yaml or in one of your extension imports:
- { resource: "EXT:generic_gallery/Configuration/Routes/Default.yaml" }

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/fnagel/generic-gallery/issues/52#issuecomment-1408870507",
"url": "https://github.com/fnagel/generic-gallery/issues/52#issuecomment-1408870507",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by fnagel** [comment]
Anhänge werden hier nicht dargestellt.

**Comment by PeterEdelmann** [comment]
Hallo, anbei übersende ich die config.yaml und die Fehlermeldung in typo3
[config.yaml.txt](https://github.com/fnagel/generic-gallery/files/10610640/config.yaml.txt)
[TYPO3 Exception.txt](https://github.com/fnagel/generic-gallery/files/10610664/TYPO3.Exception.txt)

**Comment by fnagel** [comment]
You can't just throw a line with an import into the config file. You need to use the proper syntax for importing yaml resources. Please check the documentation:

https://github.com/fnagel/generic-gallery/blob/master/Configuration/Routes/Default.yaml#L2-L3
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Routing/Introduction.html#using-imports-in-yaml-files

**Comment by fnagel** [comment]
Closed as no feedback was given. Please reopen or create a new ticket if needed.
