### ISSUE TITLE
The TYPO3 extension package "felixnagel/generic-gallery", does not define an extension key in its composer.json

### ISSUE THREAD

**Issue by mediaessenz** [fnagel/generic-gallery#57]
Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ComposerJson.html#extra)

**Comment by fnagel** [comment]
Is this about this key? https://github.com/fnagel/generic-gallery/blob/master/composer.json#L47

**Comment by mediaessenz** [comment]
Yes it's this, but never mind. I tried to install the Extension under TYPO3 11 with PHP 8.2, which brings composer to install version 1.6.0, where this key doesn't exists.
Meanwhile I updated the TYPO3 to 12 and all good.
